In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/ai4i2020.csv")

In [3]:
df.head()

,UDI,Product ID,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,HDF,PWF,OSF,RNF
0,1,M14860,M,298.1,308.6,1551,42.8,0,0,0,0,0,0,0
1,2,L47181,L,298.2,308.7,1408,46.3,3,0,0,0,0,0,0
2,3,L47182,L,298.1,308.5,1498,49.4,5,0,0,0,0,0,0
3,4,L47183,L,298.2,308.6,1433,39.5,7,0,0,0,0,0,0
4,5,L47184,L,298.2,308.7,1408,40.0,9,0,0,0,0,0,0

In [4]:
df.shape

(10000, 14)

In [5]:
df['timestamp'] = pd.date_range(
    start='2025-01-01 00:00:00',
    periods=len(df),
    freq='1min'
)

In [6]:
df[['timestamp']].head()

            timestamp
0 2025-01-01 00:00:00
1 2025-01-01 00:01:00
2 2025-01-01 00:02:00
3 2025-01-01 00:03:00
4 2025-01-01 00:04:00

In [7]:
df[['timestamp']].tail()

               timestamp
9995 2025-01-07 22:35:00
9996 2025-01-07 22:36:00
9997 2025-01-07 22:37:00
9998 2025-01-07 22:38:00
9999 2025-01-07 22:39:00

In [8]:
df['timestamp'].dtype

dtype('<M8[us]')

In [10]:
df.to_csv(
    "../data/timestamps_added.csv",
    index=False
)

print("Saved: timestamps_added.csv")

Saved: timestamps_added.csv

In [11]:
context = pd.DataFrame({
    "timestamp": df["timestamp"],
    "ambient_temperature": None,
    "load_density": None,
    "humidity": None,
    "shift": None,
    "day_type": None
})

context.head()

            timestamp ambient_temperature load_density humidity shift day_type
0 2025-01-01 00:00:00                None         None     None  None     None
1 2025-01-01 00:01:00                None         None     None  None     None
2 2025-01-01 00:02:00                None         None     None  None     None
3 2025-01-01 00:03:00                None         None     None  None     None
4 2025-01-01 00:04:00                None         None     None  None     None

In [12]:
context.to_csv(
    "../data/context_structure.csv",
    index=False
)

print("Saved: context_structure.csv")

Saved: context_structure.csv

# Week 2 Day 1 Summary

- Added timestamps to AI4I dataset.
- Created external context dataset structure.
- Created Week 2 GitHub issues.
- Updated project board and assigned responsibilities.